name: IBM Plex Sans
dateAdded: '2018-10-31'
category: Sans-Serif
styles: 16
italic: true
weights:
  - weight: 100
    name: Thin
  - weight: 200
    name: Extra-Light
  - weight: 300
    name: Light
  - weight: 400
    name: Regular
  - weight: 450
    name: Text
  - weight: 500
    name: Medium
  - weight: 600
    name: Semi-Bold
  - weight: 700
    name: Bold
latestRelease:
  version: 'v6.4.2'
  date: 16 May 2024
projectUrl: https://github.com/IBM/plex
gFontsUrl: https://fonts.google.com/specimen/IBM+Plex+Sans
creator:
  name: Mike Abbink & Bold Monday
  url: https://boldmonday.com
description: IBM Plex is the corporate typeface for IBM. The Plex family includes Serif, Sans, Sans Condensed and Mono typefaces. They are designed to work well in user interfaces, with a surprisingly expressive italic for each.
familyFaces:
  - IBM Plex Mono
  - IBM Plex Sans Condensed
  - IBM Plex Serif
comparisonFaces:
  - IBM Plex Serif
  - Libre Franklin
  - Source Sans Pro
  - Work Sans
sampleText: 'Multi-Vitamin Infusion'
sampleClasses: 'font-[300] italic'

