name: FiraGO
dateAdded: '2018-10-23'
category: Sans-Serif
styles: 22
italic: true
smallcap: true
weights:
  - weight: 100
    name: Thin
  - weight: 200
    name: UltraLight
  - weight: 250
    name: ExtraLight
  - weight: 300
    name: Light
  - weight: 350
    name: Book
  - weight: 400
    name: Regular
  - weight: 500
    name: Medium
  - weight: 600
    name: SemiBold
  - weight: 700
    name: Bold
  - weight: 800
    name: ExtraBold
  - weight: 900
    name: Heavy
latestRelease:
  version: v1.0
  date: 14 Mar 2018
projectUrl: https://github.com/bBoxType/FiraGO
creator:
  name: bBox Type
  url: https://bboxtype.com
description: FiraGO is the successor to Fira Sans and serves as the corporate typeface for Here. It is a versatile sans-serif and includes eleven weights, a well-designed italic, small caps, and good OpenType support. It works well for both long stretches of body copy and headlines.
comparisonFaces:
  - Alegreya Sans
  - IBM Plex Sans
  - Inria Sans
  - Source Sans Pro
