name: BioRhyme Expanded
dateAdded: '2018-10-28'
category: Display
styles: 5
weights:
  - weight: 200
    name: Extra-Light
  - weight: 300
    name: Light
  - weight: 400
    name: Regular
  - weight: 700
    name: Bold
  - weight: 800
    name: Extra-Bold
latestRelease:
  version: v1.600
  date: 9 Mar 2016
projectUrl: https://github.com/aoifemooney/makingbiorhyme
gFontsUrl: https://fonts.google.com/specimen/BioRhyme+Expanded
creator:
  name: Aoife Mooney
  url: http://www.aoifemooney.org
description: BioRhyme Expanded takes inspiration from older slab serifs, but adds a friendly, playful personality. It works best at large sizes, both for headlines and short bursts of body copy. BioRhyme Expanded and its sister face BioRhyme take advantage of OpenType enhancements including alternative glyph forms, swashes and emoticons.
familyFaces:
  - BioRhyme
comparisonFaces:
  - BioRhyme
sampleText: 'fat burger'
sampleClasses: 'font-[800] uppercase'
