name: TASA Orbiter
dateAdded: '2023-10-22'
category: Sans-Serif
styles: Variable
weights:
  - weight: 400
    name: Regular
  - weight: 500
    name: Medium
  - weight: 600
    name: SemiBold
  - weight: 700
    name: Bold
  - weight: 900
    name: Black
latestRelease:
  version: 'v2.012'
  date: 16 Oct 2025
projectUrl: https://github.com/localremotetw/TASA-Typeface-Collection
creator:
  name: Local Remote
  url: https://localremote.co
description: Bespoke typeface designed for the rebrand of Taiwan Space Agency. Neo-Grotesques and right-angled strokes designed for versatility across a broad range of applications for everyday use.
comparisonFaces:
  - Archivo
  - Fivo Sans
  - iA Writer Quattro
