name: Rakkas
dateAdded: '2018-10-22'
category: Display
styles: 1
weights:
  - weight: 400
    name: Regular
latestRelease:
  version: v1.001
  date: 10 Apr 2016
projectUrl: https://github.com/zeynepakay/Rakkas
gFontsUrl: https://fonts.google.com/specimen/Rakkas
creator:
  name: Zeynep Akay
  url: http://theruqahproject.com
description: Rakkas is a single-weight display typeface supporting both Arabic and Latin scrips. The Latin is based on a blackletter style, but borrows heavily from the Arabic design, with heavy calligraphic strokes.
