name: Le Murmure
dateAdded: '2018-11-25'
category: Display
styles: 1
weights:
  - weight: 400
    name: Regular
latestRelease:
  version: v1.1
  date: 10 Jul 2019
projectUrl: https://velvetyne.fr/fonts/le-murmure/
creator:
  name: Jérémy Landes
  url: http://studiotriple.fr
description: Designed especially for the French design agency <a href='https://murmure.me/'>Murmure</a>, Le Murmure is a distinctive sans-serif display typeface. Available in a single weight, it features a wealth of alternate glyphs.
sampleText: 'Oneohtrix Point Never'
sampleClasses: 'font-[400] tracking-tight'
