name: Source Sans Pro
dateAdded: '2018-11-27'
category: Sans-Serif
styles: Variable
italic: true
smallcap: true
weights:
  - weight: 200
    name: Extra Light
  - weight: 300
    name: Light
  - weight: 400
    name: Regular
  - weight: 500
    name: Medium
  - weight: 600
    name: Semi Bold
  - weight: 700
    name: Bold
  - weight: 800
    name: Extra Bold
  - weight: 900
    name: Black
latestRelease:
  version: 'v3.052R'
  date: 4 Apr 2023
projectUrl: https://github.com/adobe-fonts/source-sans-pro
gFontsUrl: https://fonts.google.com/specimen/Source+Sans+3
creator:
  name: Paul D. Hunt
  url: https://github.com/pauldhunt
description: Source Sans Pro is a versatile typeface designed particularly for user interfaces. Its letterforms are slightly condensed allowing them to fit into tight spaces within a UI, and remain well-defined even at small sizes.
familyFaces:
  - Source Code Pro
  - Source Serif Pro
comparisonFaces:
  - Source Serif Pro
  - Archivo
  - FiraGO
  - Inria Sans
sampleText: 'Café de la Paix'
sampleClasses: 'font-[700] tracking-tight'
