name: Fira Code
dateAdded: '2019-01-21'
category: Monospaced
styles: Variable
sampleShade: light
weights:
  - weight: 300
    name: Light
  - weight: 400
    name: Regular
  - weight: 500
    name: Medium
  - weight: 700
    name: Bold
latestRelease:
  version: 'v6.2'
  date: 6 Dec 2021
projectUrl: https://github.com/tonsky/FiraCode
creator:
  name: Nikita Prokopov
  url: https://twitter.com/nikitonsky
description: Fira Code is a monospaced typeface optimized for reading and writing code. It has a huge number of ligatures catering to a variety of programming languages, making code more concise and readable.
comparisonFaces:
  - IBM Plex Mono
  - Source Code Pro
  - Space Mono
